#!/bin/bash
cd Desktop/Github/IPD_PF
./split PF.svg -i -k art -k bevel -k drill -k rout
./split PF.svg -i -k art
./split PF.svg    -k assembly
./split PF.svg    -k bevel -k drill -k rout
./split PF.svg    -k bevel
./split PF.svg    -k bottom
./split PF.svg    -k drill
./split PF.svg    -k hdrill
./split PF.svg    -k tdrill
./split PF.svg    -k bdrill
./split PF.svg    -k habitrails
./split PF.svg    -k metal -k habitrails
./split PF.svg    -k metal
./split PF.svg -i -k plastic
./split PF.svg    -k rout
./split PF.svg    -k trout
./split PF.svg    -k brout
./split PF.svg    -k rubber
./split PF.svg -i -k sticker
./split PF.svg    -k todo
./split PF.svg    -k top
./split PF.svg    -k woodwalls
# ./split PF.svg -a -k rout -k top
# ./split PF.svg -a -k rout -k bottom


./dpi PF.art.bevel.drill.rout.svg
./dpi PF.art.svg
./dpi PF.assembly.svg
./dpi PF.bevel.drill.rout.svg
./dpi PF.bevel.svg
./dpi PF.bottom.svg
./dpi PF.drill.svg
./dpi PF.hdrill.svg
./dpi PF.tdrill.svg
./dpi PF.bdrill.svg
./dpi PF.habitrails.svg
./dpi PF.metal.habitrails.svg
./dpi PF.metal.svg
./dpi PF.plastic.svg
./dpi PF.rout.svg
./dpi PF.trout.svg
./dpi PF.brout.svg
./dpi PF.rubber.svg
./dpi PF.sticker.svg
./dpi PF.todo.svg
./dpi PF.top.svg
./dpi PF.woodwalls.svg