#!/bin/bash
cd Desktop/Github/IPD_PF
./split PF.svg -k drill
# ./split PF.svg -a -k rout -k top
# ./split PF.svg -a -k rout -k bottom
./split PF.svg -k rout
./split PF.svg -k bevel
./split PF.svg -k rout -k bevel -k drill
./split PF.svg -k plastic
./split PF.svg -k art
./split PF.svg -k metal
./split PF.svg -k sticker
./split PF.svg -k assembly
./split PF.svg -k top
./split PF.svg -k bottom
./split PF.svg -k rubber
./split PF.svg -k todo




